#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd -- "$(dirname -- "$0")/.."

echo "==> Cleaning up..."
exec -- rm -fr -- ./vendor/ ./.php-cs-fixer.cache
